import { Task, Project, WorkspaceFile, SessionStats } from './types';

export const workspaceFiles: WorkspaceFile[] = [
  { name: 'HEARTBEAT.md', icon: '❤️', timestamp: 'il y a 1h' },
  { name: 'USER.md', icon: '👤', timestamp: 'il y a 23h' },
  { name: 'TOOLS.md', icon: '🔧', timestamp: 'il y a 1j' },
  { name: 'MEMORY.md', icon: '🧠', timestamp: 'il y a 2j' },
  { name: 'IDENTITY.md', icon: '🆔', timestamp: 'il y a 3j' },
  { name: 'AGENTS.md', icon: '📋', timestamp: 'il y a 3j' },
  { name: 'SOUL.md', icon: '✨', timestamp: 'il y a 3j' },
];

export const sessionStats: SessionStats = {
  messages: 619,
  tools: 7,
};

export const initialProjects: Project[] = [
  {
    id: '1',
    name: 'Extensions Chrome',
    status: 'active',
    description: 'Développement extensions Chrome pour productivité',
    progress: 45,
    phase: 'Phase 2 - Développement UI',
    milestones: { total: 15, completed: 7 },
    startedAt: '2026-01-15',
    version: 'v1.0.0-beta',
    nextSteps: [
      'Finaliser interface popup',
      'Intégrer API backend',
      'Tests utilisateurs',
    ],
  },
  {
    id: '2',
    name: 'Affiliation',
    status: 'active',
    description: 'Projet affiliation marketing full-time',
    progress: 81,
    phase: 'Phase 3 - Optimisation & Tracking',
    milestones: { total: 20, completed: 16 },
    startedAt: '2026-01-01',
    version: 'v2.1.0',
    nextSteps: [
      'Dashboard analytics',
      'Automatisation rapports',
      'Intégration nouveaux sites',
    ],
  },
  {
    id: '3',
    name: 'Michel Dashboard',
    status: 'planning',
    description: 'Dashboard de gestion complet',
    progress: 66,
    phase: 'Phase 3 - Kanban 6 colonnes & Cards riches',
    milestones: { total: 28, completed: 18 },
    startedAt: '2026-01-30',
    version: 'v1.3.0-dev',
    nextSteps: [
      '6 colonnes Kanban',
      'Cards enrichies',
      'Right Panel Mental State',
    ],
  },
];

export const initialTasks: Task[] = [
  // IDEAS
  {
    id: '1',
    title: 'Système de notifications push',
    description: 'Ajouter notifications navigateur pour cronjobs',
    status: 'ideas',
    priority: 'medium',
    project: 'Michel Dashboard',
    tags: ['feature', 'notifications'],
    assignedTo: 'Michel',
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-03'),
    progress: 0,
    subtasks: [
      { id: '1-1', text: 'Rechercher API notifications', completed: false },
      { id: '1-2', text: 'Créer composant notification', completed: false },
      { id: '1-3', text: 'Intégrer avec cronjobs', completed: false },
    ],
    links: [
      { id: '1-l1', type: 'doc', label: 'Documentation API', url: '#', icon: '📁' },
      { id: '1-l2', type: 'memory', label: 'Notes brainstorming', url: '#', icon: '🔧' },
    ],
    autoCreated: false,
    autoPickup: false,
  },
  // BACKLOG
  {
    id: '2',
    title: 'Intégration Git dans cards',
    description: 'Liens vers repos Git et commits',
    status: 'backlog',
    priority: 'high',
    project: 'Michel Dashboard',
    tags: ['integration', 'git'],
    assignedTo: 'Michel',
    createdAt: new Date('2026-01-28'),
    updatedAt: new Date('2026-02-02'),
    progress: 15,
    subtasks: [
      { id: '2-1', text: 'Étudier GitHub API', completed: true },
      { id: '2-2', text: 'Créer composant Git links', completed: false },
      { id: '2-3', text: 'Ajouter icônes branches', completed: false },
      { id: '2-4', text: 'Lien vers derniers commits', completed: false },
    ],
    links: [
      { id: '2-l1', type: 'git', label: 'Repo GitHub', url: 'https://github.com', icon: '🔀' },
      { id: '2-l2', type: 'doc', label: 'GitHub API Docs', url: '#', icon: '📁' },
    ],
    autoCreated: true,
    autoPickup: false,
  },
  {
    id: '3',
    title: 'Mode mobile responsive',
    description: 'Adapter layout pour mobile/tablet',
    status: 'backlog',
    priority: 'medium',
    project: 'Michel Dashboard',
    tags: ['ui', 'responsive'],
    assignedTo: 'Michel',
    createdAt: new Date('2026-01-30'),
    updatedAt: new Date('2026-02-01'),
    progress: 25,
    subtasks: [
      { id: '3-1', text: 'Design mobile mockups', completed: true },
      { id: '3-2', text: 'Breakpoints CSS', completed: false },
      { id: '3-3', text: 'Navigation mobile', completed: false },
      { id: '3-4', text: 'Tests responsive', completed: false },
    ],
    links: [
      { id: '3-l1', type: 'doc', label: 'Figma Designs', url: '#', icon: '📁' },
      { id: '3-l2', type: 'memory', label: 'UX Notes', url: '#', icon: '🔧' },
    ],
    autoCreated: false,
    autoPickup: true,
  },
  // TO DO
  {
    id: '4',
    title: 'Sidebar complète avec fichiers workspace',
    description: 'Implémenter sections Status, Files, Stats',
    status: 'todo',
    priority: 'high',
    project: 'Michel Dashboard',
    tags: ['sprint1', 'sidebar'],
    assignedTo: 'Michel',
    createdAt: new Date('2026-02-04'),
    updatedAt: new Date('2026-02-04'),
    progress: 0,
    subtasks: [
      { id: '4-1', text: 'Avatar section avec XP bar', completed: false },
      { id: '4-2', text: 'Status card avec citation', completed: false },
      { id: '4-3', text: 'Workspace files list', completed: false },
      { id: '4-4', text: 'Session stats', completed: false },
      { id: '4-5', text: 'Navigation menu', completed: false },
    ],
    links: [
      { id: '4-l1', type: 'doc', label: 'Specs Design', url: '#', icon: '📁' },
      { id: '4-l2', type: 'session', label: 'Session Claude', url: '#', icon: '💬' },
      { id: '4-l3', type: 'git', label: 'Branch sidebar', url: '#', icon: '🔀' },
    ],
    autoCreated: false,
    autoPickup: false,
  },
  {
    id: '5',
    title: 'Main dashboard avec stats',
    description: 'Cards stats + greeting + travail en cours',
    status: 'todo',
    priority: 'high',
    project: 'Michel Dashboard',
    tags: ['sprint1', 'dashboard'],
    assignedTo: 'Michel',
    createdAt: new Date('2026-02-04'),
    updatedAt: new Date('2026-02-04'),
    progress: 0,
    subtasks: [
      { id: '5-1', text: 'Greeting card avec gradient', completed: false },
      { id: '5-2', text: '3 stats cards horizontales', completed: false },
      { id: '5-3', text: 'Currently Working On section', completed: false },
      { id: '5-4', text: 'System Status indicators', completed: false },
    ],
    links: [
      { id: '5-l1', type: 'doc', label: 'DESIGN-SPECS.md', url: '#', icon: '📁' },
      { id: '5-l2', type: 'memory', label: 'Layout notes', url: '#', icon: '🔧' },
    ],
    autoCreated: true,
    autoPickup: true,
  },
  {
    id: '6',
    title: 'Kanban 6 colonnes',
    description: 'Passer de 3 à 6 colonnes avec drag & drop',
    status: 'todo',
    priority: 'high',
    project: 'Michel Dashboard',
    tags: ['sprint1', 'kanban'],
    assignedTo: 'Michel',
    createdAt: new Date('2026-02-04'),
    updatedAt: new Date('2026-02-04'),
    progress: 0,
    subtasks: [
      { id: '6-1', text: 'Setup @dnd-kit/core', completed: false },
      { id: '6-2', text: 'Créer 6 colonnes', completed: false },
      { id: '6-3', text: 'Drag & drop logic', completed: false },
      { id: '6-4', text: 'Animations transitions', completed: false },
      { id: '6-5', text: 'Persistence Zustand', completed: false },
    ],
    links: [
      { id: '6-l1', type: 'doc', label: 'dnd-kit docs', url: '#', icon: '📁' },
      { id: '6-l2', type: 'git', label: 'Feature branch', url: '#', icon: '🔀' },
    ],
    autoCreated: false,
    autoPickup: false,
  },
  {
    id: '7',
    title: 'Optimiser landing page affiliation',
    description: 'Améliorer SEO et temps de chargement',
    status: 'todo',
    priority: 'high',
    project: 'Affiliation',
    tags: ['seo', 'performance'],
    assignedTo: 'Michel',
    createdAt: new Date('2026-02-02'),
    updatedAt: new Date('2026-02-04'),
    progress: 20,
    subtasks: [
      { id: '7-1', text: 'Audit Lighthouse', completed: true },
      { id: '7-2', text: 'Optimiser images', completed: false },
      { id: '7-3', text: 'Meta tags SEO', completed: false },
      { id: '7-4', text: 'Schema markup', completed: false },
      { id: '7-5', text: 'Lazy loading', completed: false },
    ],
    links: [
      { id: '7-l1', type: 'doc', label: 'SEO Checklist', url: '#', icon: '📁' },
      { id: '7-l2', type: 'memory', label: 'Performance notes', url: '#', icon: '🔧' },
      { id: '7-l3', type: 'git', label: 'Repo affiliation', url: '#', icon: '🔀' },
    ],
    autoCreated: false,
    autoPickup: true,
  },
  // IN PROGRESS
  {
    id: '8',
    title: 'Développer popup extension',
    description: 'Interface utilisateur principale extension',
    status: 'inprogress',
    priority: 'high',
    project: 'Extensions Chrome',
    tags: ['ui', 'react'],
    assignedTo: 'Michel',
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-04'),
    startedAt: new Date('2026-02-03'),
    progress: 65,
    subtasks: [
      { id: '8-1', text: 'Setup React + Vite', completed: true },
      { id: '8-2', text: 'Design layout popup', completed: true },
      { id: '8-3', text: 'Intégrer Tailwind CSS', completed: true },
      { id: '8-4', text: 'Composants réutilisables', completed: false },
      { id: '8-5', text: 'State management', completed: false },
      { id: '8-6', text: 'Chrome API integration', completed: false },
    ],
    links: [
      { id: '8-l1', type: 'git', label: 'Extension repo', url: '#', icon: '🔀' },
      { id: '8-l2', type: 'doc', label: 'Chrome API docs', url: '#', icon: '📁' },
      { id: '8-l3', type: 'session', label: 'Dev session', url: '#', icon: '💬' },
    ],
    autoCreated: false,
    autoPickup: false,
  },
  // REVIEW
  {
    id: '9',
    title: 'Tests API extensions',
    description: 'Validation endpoints et gestion erreurs',
    status: 'review',
    priority: 'medium',
    project: 'Extensions Chrome',
    tags: ['tests', 'api'],
    assignedTo: 'Michel',
    createdAt: new Date('2026-01-28'),
    updatedAt: new Date('2026-02-03'),
    startedAt: new Date('2026-02-01'),
    progress: 85,
    subtasks: [
      { id: '9-1', text: 'Tests unitaires endpoints', completed: true },
      { id: '9-2', text: 'Tests intégration', completed: true },
      { id: '9-3', text: 'Gestion erreurs 4xx', completed: true },
      { id: '9-4', text: 'Gestion erreurs 5xx', completed: true },
      { id: '9-5', text: 'Documentation API', completed: false },
      { id: '9-6', text: 'Code review', completed: false },
    ],
    links: [
      { id: '9-l1', type: 'git', label: 'Pull Request #42', url: '#', icon: '🔀' },
      { id: '9-l2', type: 'doc', label: 'Test results', url: '#', icon: '📁' },
      { id: '9-l3', type: 'memory', label: 'Review notes', url: '#', icon: '🔧' },
    ],
    autoCreated: true,
    autoPickup: false,
  },
  // DONE
  {
    id: '10',
    title: 'Setup Next.js 14 avec TypeScript',
    description: 'Initialisation projet dashboard',
    status: 'done',
    priority: 'high',
    project: 'Michel Dashboard',
    tags: ['setup', 'typescript'],
    assignedTo: 'Michel',
    createdAt: new Date('2026-01-30'),
    updatedAt: new Date('2026-01-30'),
    startedAt: new Date('2026-01-30'),
    completedAt: new Date('2026-01-30'),
    progress: 100,
    subtasks: [
      { id: '10-1', text: 'Create Next.js app', completed: true },
      { id: '10-2', text: 'Configure TypeScript', completed: true },
      { id: '10-3', text: 'Setup Tailwind CSS', completed: true },
      { id: '10-4', text: 'Configure ESLint', completed: true },
    ],
    links: [
      { id: '10-l1', type: 'git', label: 'Initial commit', url: '#', icon: '🔀' },
      { id: '10-l2', type: 'doc', label: 'Next.js docs', url: '#', icon: '📁' },
    ],
    autoCreated: false,
    autoPickup: false,
  },
  {
    id: '11',
    title: 'Dashboard analytics affiliation',
    description: 'Tableau de bord statistiques revenus',
    status: 'done',
    priority: 'high',
    project: 'Affiliation',
    tags: ['analytics', 'dashboard'],
    assignedTo: 'Michel',
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-01-28'),
    startedAt: new Date('2026-01-22'),
    completedAt: new Date('2026-01-28'),
    progress: 100,
    subtasks: [
      { id: '11-1', text: 'Connexion API affiliation', completed: true },
      { id: '11-2', text: 'Graphiques revenus', completed: true },
      { id: '11-3', text: 'Statistiques temps réel', completed: true },
      { id: '11-4', text: 'Export données CSV', completed: true },
      { id: '11-5', text: 'Tests utilisateurs', completed: true },
    ],
    links: [
      { id: '11-l1', type: 'git', label: 'Repo analytics', url: '#', icon: '🔀' },
      { id: '11-l2', type: 'doc', label: 'API documentation', url: '#', icon: '📁' },
      { id: '11-l3', type: 'session', label: 'Deploy notes', url: '#', icon: '💬' },
    ],
    autoCreated: false,
    autoPickup: false,
  },
];
