import { Task, Column } from '@/types/types';

export const columns: Column[] = [
  { id: 'todo', title: 'To Do', status: 'todo' },
  { id: 'in-progress', title: 'In Progress', status: 'in-progress' },
  { id: 'done', title: 'Done', status: 'done' },
];

export const initialTasks: Task[] = [
  {
    id: '1',
    title: 'Design authentication flow',
    description: 'Create wireframes and user flow diagrams for the login/signup process',
    status: 'todo',
    priority: 'high',
    assignee: {
      name: 'Sarah Chen',
      avatar: '/avatars/sarah.jpg',
    },
    dueDate: new Date('2026-02-06'),
    tags: ['design', 'ux', 'authentication'],
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: '2',
    title: 'Implement API rate limiting',
    description: 'Add rate limiting middleware to protect API endpoints from abuse',
    status: 'todo',
    priority: 'high',
    assignee: {
      name: 'Marcus Rodriguez',
      avatar: '/avatars/marcus.jpg',
    },
    dueDate: new Date('2026-02-08'),
    tags: ['backend', 'security', 'api'],
    createdAt: new Date('2026-02-02'),
    updatedAt: new Date('2026-02-02'),
  },
  {
    id: '3',
    title: 'Update documentation',
    description: 'Revise API documentation to include new endpoints and authentication methods',
    status: 'todo',
    priority: 'medium',
    assignee: {
      name: 'Emily Watson',
      avatar: '/avatars/emily.jpg',
    },
    dueDate: new Date('2026-02-10'),
    tags: ['documentation', 'api'],
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-03'),
  },
  {
    id: '4',
    title: 'Build dashboard analytics widget',
    description: 'Create interactive charts showing user engagement metrics',
    status: 'in-progress',
    priority: 'high',
    assignee: {
      name: 'David Park',
      avatar: '/avatars/david.jpg',
    },
    dueDate: new Date('2026-02-07'),
    tags: ['frontend', 'react', 'analytics'],
    createdAt: new Date('2026-01-28'),
    updatedAt: new Date('2026-02-04'),
  },
  {
    id: '5',
    title: 'Fix responsive layout issues',
    description: 'Address mobile viewport problems on product pages',
    status: 'in-progress',
    priority: 'medium',
    assignee: {
      name: 'Sarah Chen',
      avatar: '/avatars/sarah.jpg',
    },
    dueDate: new Date('2026-02-05'),
    tags: ['frontend', 'css', 'responsive'],
    createdAt: new Date('2026-02-02'),
    updatedAt: new Date('2026-02-04'),
  },
  {
    id: '6',
    title: 'Optimize database queries',
    description: 'Identify and optimize slow queries in the user dashboard',
    status: 'in-progress',
    priority: 'high',
    assignee: {
      name: 'Marcus Rodriguez',
      avatar: '/avatars/marcus.jpg',
    },
    dueDate: new Date('2026-02-06'),
    tags: ['backend', 'database', 'performance'],
    createdAt: new Date('2026-01-30'),
    updatedAt: new Date('2026-02-03'),
  },
  {
    id: '7',
    title: 'Setup CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing and deployment',
    status: 'done',
    priority: 'high',
    assignee: {
      name: 'Alex Johnson',
      avatar: '/avatars/alex.jpg',
    },
    dueDate: new Date('2026-02-03'),
    tags: ['devops', 'ci-cd', 'automation'],
    createdAt: new Date('2026-01-25'),
    updatedAt: new Date('2026-02-03'),
  },
  {
    id: '8',
    title: 'User research interviews',
    description: 'Conduct 5 user interviews to gather feedback on new features',
    status: 'done',
    priority: 'medium',
    assignee: {
      name: 'Emily Watson',
      avatar: '/avatars/emily.jpg',
    },
    dueDate: new Date('2026-02-01'),
    tags: ['research', 'ux', 'user-testing'],
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: '9',
    title: 'Implement dark mode',
    description: 'Add theme toggle and dark mode styles across the application',
    status: 'todo',
    priority: 'low',
    assignee: {
      name: 'David Park',
      avatar: '/avatars/david.jpg',
    },
    dueDate: new Date('2026-02-15'),
    tags: ['frontend', 'ui', 'accessibility'],
    createdAt: new Date('2026-02-03'),
    updatedAt: new Date('2026-02-03'),
  },
  {
    id: '10',
    title: 'Write unit tests for auth module',
    description: 'Achieve 80% test coverage for authentication service',
    status: 'todo',
    priority: 'medium',
    assignee: {
      name: 'Alex Johnson',
      avatar: '/avatars/alex.jpg',
    },
    dueDate: new Date('2026-02-12'),
    tags: ['testing', 'backend', 'quality'],
    createdAt: new Date('2026-02-02'),
    updatedAt: new Date('2026-02-02'),
  },
];
